### ISSUE TITLE
Pressing escape on import file fields hides legend

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1928] opened 2017-06-01 17:19 UTC
While focusing on any input field while importing a file layer, pressing 'esc' will hide the entire legend. However, while not in focus on an input field, 'esc' has no action.

![legend](https://cloud.githubusercontent.com/assets/9637542/26691872/c20848aa-46cc-11e7-9b65-c55a4ed9070a.JPG)

**Comment by milesap** [comment] 2017-06-01 18:10
A little background info:

A panel can have multiple child panels defined, however, only one child can be open at a time. So when the file import panel is opened, the legend panel is closed. A history of ordered active panels is maintained so pressing escape closes panels in the order they were opened. 

Clicking on the close button itself is different, as we explicitly open the legend panel (which in turn closes the file import panel).
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/loader/loader-file.directive.js#L367

I can't see an easy way to change this. One way is to upgrade the panel history such that when a sibling panel closes another, the close panel is added to the history. We would then toggle instead of close panels in the history.

Just to confirm, is focus within the document or the window? We can't watch the window, so this could explain the no action on escape key press.

**Comment by JahidAhmed** [comment] 2017-06-01 18:48
Focus is on the window.

Also, clicking on the map and pressing escape closes the open panel, however an `Uncaught TypeError: Cannot read property 'extent' of undefined` occurs

**Comment by milesap** [comment] 2017-06-09 11:32
Opened #1947 - closing as not a bug

**Closed by milesap** 2017-06-09 11:32 UTC
Labels: needs: more info, needs: UX review, problem: bug
