### ISSUE TITLE
Layer remove event error

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3515] opened 2019-05-22 15:37 UTC
Hi,

When i try to catch the layerRemoved event (```this.api.layersObj.layerRemoved.subscribe```)  there is this error:

```TypeError: layerRecord.removeFilterListener is not a function
    at Object.removeLayerRecord (layer-registry.service.js:365)
    at _resolve (legend.service.js:447)
    at eval (toc.service.js:287)
    at processQueue (angular.js:17914)
    at eval (angular.js:17962)
    at Scope.$digest (angular.js:19075)
    at eval (angular.js:19395)
    at TaskTracker.completeTask (angular.js:21194)
    at eval (angular.js:6790) "Possibly unhandled rejection: {}"```

It use to works in the latest version

**Comment by milesap** [comment] 2019-05-22 19:00
I couldn't replicate this on a [develop sample](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html) with `RAMP.mapInstances[0].layers.layerRemoved.subscribe(console.error);` in dev tools - adding the service http://section917.cloudapp.net/arcgis/rest/services/EcoGeo/MapServer/6 then subsequently removing it through the legend UI.

Please post detailed steps on how to replicate this issue.

**Comment by james-rae** [comment] 2019-05-22 19:08
Perhaps the version/build of ramp being used, and if it's a layer url that's publically available would be helpful.

**Comment by jolevesq** [comment] 2019-05-24 11:22
Hi,

This is the version: RVersion = {"major":"3","minor":"0","patch":"0","timestamp":1554485448722,"gitHash":"d55be572fe8d6415f2174fe1f0e4117983ec44ca"}

I use this to load the layer: ```this._RV.loadRcsLayers([uuid]);``` uuid = 3d282116-e556-400c-9306-ca1a3cada77f

And I have the error here: ``` this.api.layersObj.layerRemoved.subscribe((layer: any) => myFunction(layer));```

**Comment by JahidAhmed** [comment] 2019-05-24 16:01
The error being thrown is on [this](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/layer-registry.service.js#L293) line and the reason is because the RCS layer being adding is a WMS layer and it doesn't have a `removeFilterListener` function since that function is inside of `attribRecord.js` [here](https://github.com/fgpv-vpgf/geoApi/blob/v3.0.0-13/src/layer/layerRec/attribRecord.js#L251) and WMS layers do not have attributes, so this function does not exist for them. 

I also confirmed the error also gets thrown for the other WMS layer currently on sample 1, so it's not RCS related.

**Comment by jolevesq** [comment] 2019-05-28 13:26
@JahidAhmed can you please let me know when this will be solve? I need to provide a build with this bug resolve by the end of the week. Thanks!

**Comment by JahidAhmed** [comment] 2019-05-28 13:38
Hi @jolevesq! I'm hoping to PR the fix today and get it merged in tomorrow if James is back in the office!

**Comment by jolevesq** [comment] 2019-05-28 15:21
@JahidAhmed Thanks a lot

**Closed** 2019-05-31 17:49 UTC
Labels: bug-type: broken use case, problem: bug
