### ISSUE TITLE
Export locks Firefox

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1532] opened 2016-12-20 14:26 UTC
May not be related to this PR, but on Firefox:

- export
- custom size
- click generate without picking a size
- export disappears and focus manager pops up with keyboard focus prompt
- click export again
- browser locks up

Reported by @alyec

**Comment by AleksueiR** [comment] 2016-12-21 19:41
Locks up on Chrome as well:
- export
- select custom size 
- close export dialog without (no need to generate an image)
- export again
- browsers hangs up

**Comment by milesap** [comment] 2016-12-23 14:55
This issue is not caused by focus manager - browser crashes with focus manager removed entirely. I'll assign this to @AleksueiR as well who may know what is causing this. I'll also continue to poke at it.

**Comment by AleksueiR** [comment] 2016-12-29 13:49
If the export dialog is closed without setting a valid export size (height and width are defined), the next time the dialog is opened, this invalid size is applied locking the browser. The fix involves resetting the invalid export size to the default one, when detected.

**Comment by bkutty** [comment] 2017-01-12 15:14
No longer an issue as verified on build v1.5.0.10

**Closed** 2017-01-23 14:02 UTC
Labels: bug-type: broken use case, experience: ux, priority: high, problem: bug, v1.5.0
