### ISSUE TITLE
WFS slow to be recognized by import wizard

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3432] opened 2019-04-25 17:44 UTC
Putting a WFS service url in the import wizard results in a timely wait for step 2 of the wizard to appear.

This is not a service speed issue; if the same WFS layer is loaded via config, it's a rocket.

Possibly something in the "guess the service type" logic is stalling/timing out.

Could be related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2937

Also, there may have been an unofficial discussion to remove the prediction altogether and force the user to pick the service type.  Would need a discussion before implementing that, but if we do, then this issue is moot.

**Comment by RyanCoulsonCA** [comment] 2019-08-16 15:06
Looked into this a little bit while working on the wizard. From what I can tell, it looks like the problem was caused by making an ESRI request with the WFS url. The promise returned by the `esriRequest` method was what was taking a very long time to resolve.

In my PR that removes active prediction from the wizard (https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3709), this step is skipped since the user has to specify that the service is WFS. This issue should be fixed once that PR is merged.

NOTE: if the user incorrectly chooses the format of a WFS service while importing, this long wait time will still occur since there's no way to tell that the user was incorrect until the promise resolves. This could be solved by setting a timeout, but this could cause other problems.

**Comment by mpath** [comment] 2019-09-06 13:36
Tested in Build: V3.2.0-b1
Issue resolved.

**Closed** 2019-10-04 15:47 UTC
Labels: problem: performance, type: corrective
