### ISSUE TITLE
Navigation Controls stuck in middle of Viewer

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#469] opened 2016-04-07 13:27 UTC
- Basemap selector is opened, pushes navigation control over
- Datagrid opens, closing basemap selector, but navigation controls remain where they are

**Comment by AleksueiR** [comment] 2016-05-24 00:40
Duplicate of #139.

**Closed by AleksueiR** 2016-05-24 00:40 UTC
Labels: bug-type: broken use case, priority: medium, problem: bug
