### ISSUE TITLE
EnhancedTable: hidden default column breaks table filter

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3494] opened 2019-05-15 17:04 UTC
Found by @JahidAhmed 

Steps to reproduce using below config snippet: 
- Clear table filters
- Show the hidden `OBJECTID` column
- Add a column filter to the `OBJECTID` column
- Hide the `OBJECTID` column again
- Close the table
- Reopen the table --> the table isn't filtered! 
- Unhide `OBJECTID` column --> table is filtered as expected

Expected behaviour: table should be filtered even when column is hidden because the filter is still technically applied to the `OBJECTID` column

Config snippet for layers and legend: 

```js
    "legend": {
      "type": "autopopulate"
    },
    "layers": [{
        "id": "0",
        "name": "Electric Transmission Line",
        "layerType": "esriFeature",
        "table": {
          "columns": [{
            "data": "OBJECTID",
            "title": "OBJECTID",
            "visible": false,
            "searchable": true,
            "filter": {
              "type": "number",
              "value": "0,80"
            }
          }]
        },
        "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/1"
      }]
```

**Comment by JahidAhmed** [comment] 2019-05-16 15:06
The issue is a lot easier to reproduce (and more generic) than the steps we initially outlined above.

Tested on: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html?sample=88

Open `Liquids Pipeline` (see it's filtered) -> close it -> open it again (see it's not filtered).

The issue seems to be happening here: https://github.com/fgpv-vpgf/plugins/blob/develop/enhancedTable/custom-floating-filters.ts#L259 - this line is not being hit the second time around

**Comment by JahidAhmed** [comment] 2019-05-16 17:18
There are 2 other bugs I've noticed:
- Applying filters to map and closing and reopening the table will again enable the button to be clickable
- Hiding a layer with a filter and then closing and reopening the table will disable the clear filters button (though this might be a direct result of the issue above, and fix itself whenever that is resolved)

Overall, seems like there are a couple similar type of issues with reopening the datatable

**Comment by YaroRoodzit** [comment] 2019-06-11 18:24
Tested build: v3.1.0-b1
Test sample: 88
Works properly with Chrome , but unexpected behavior and errors with IE.
- SCRIPT16389: Unspecified error.
readyException.js (9,1)
- SCRIPT5022: ag-Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, eg instead of api.refreshView(), call setTimeout(function(){api.refreshView(),0}). To see what part of your code that caused the refresh check this stacktrace.
readyException.js (9,1)
focusManager You cannot use *rvFocus* on elements that are outside the viewer
- SCRIPT5022: ag-Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, eg instead of api.refreshView(), call setTimeout(function(){api.refreshView(),0}). To see what part of your code that caused the refresh check this stacktrace.
rowRenderer.js (266,1)


![image](https://user-images.githubusercontent.com/38046459/59296578-5011dc00-8c54-11e9-81bf-7acf4d068dd4.png)

**Comment by james-rae** [comment] 2019-06-11 18:26
Worth noting this does not happen on my PC, but have seen it done in a repeatable manner on Yaro's. Certainly worth having some more people give it a try and see what happens.

**Comment by ShrutiVellanki** [comment] 2019-06-11 18:34
I don't get any of Yaro's errors in IE, my table doesn't open and is forever in `Building...` state.

However I do get the following error: 

![image](https://user-images.githubusercontent.com/25359812/59297315-075b2280-8c56-11e9-822d-a337c77fb81e.png)

**Comment by JahidAhmed** [comment] 2019-06-11 18:36
I'm getting the same problems as Shruti mentioned above. the error she mentioned also results in that layer (Keyword search) not being added to the legend

**Comment by YaroRoodzit** [comment] 2019-06-11 18:42
Something happened and layer "keyword search" are not visible any more.
![image](https://user-images.githubusercontent.com/38046459/59297800-18586380-8c57-11e9-8892-7a034f352841.png)

**Comment by ShrutiVellanki** [comment] 2019-06-11 18:53
For whoever picks this up: 

![image](https://user-images.githubusercontent.com/25359812/59298344-5b670680-8c58-11e9-9f02-3439a8a200be.png)

The null object is `mApi`. Fix could be as easy as checking: 
- if `mApi === null`, wait for `events.rvApiMapAdded` or `events.rvMapLoaded` to fire before executing rest of block

**Comment by ShrutiVellanki** [comment] 2019-06-14 20:07
I am unable to reproduce this error as of today: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html?sample=88

If I had to guess I'm guessing the changes in [Yi Lei's PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3578/files) to `legend.service.js` and also `layer-registry.service.js` fixed it but i'm not sure. 

A second pair of :eyes: would be appreciated

**Comment by james-rae** [comment] 2019-06-14 20:10
Still WOMM

**Comment by JahidAhmed** [comment] 2019-06-14 20:26
WOMM now too

**Comment by YaroRoodzit** [comment] 2019-06-19 21:24
Have you tried Edge? Works great with IE or Chrome. The "keyword search" layer is not loaded into the Edge.

**Comment by james-rae** [comment] 2019-06-20 18:52
I get the failure as well.  Looks like something in Edge causes a security violation when connecting to a service on the development server.  Can someone change sample 88 to use the production version of that layer?
`http://maps-cartes.ec.gc.ca/arcgis/rest/services/CAM/MapServer`

**Comment by ShrutiVellanki** [comment] 2019-06-20 18:55
yup works with production version will PR

**Comment by YaroRoodzit** [comment] 2019-07-04 15:51
Re-tested with build : v3.1.0.-b4
Issue solved for all browsers.

**Closed** 2019-08-23 18:23 UTC
Labels: bug-type: broken use case, problem: bug, type: corrective
