### ISSUE TITLE
Zoom To Feature not working on Feature Details panel for user added CESI layers

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1688] opened 2017-02-10 20:01 UTC
Tested build: http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

• Import above test data to add CESI layer, select some sub-layers for example Water
• Click any map point to open Feature Details panel
• Click Zoom To Feature button on the panel
 The map is not zooming to the selected map point.

![image](https://cloud.githubusercontent.com/assets/18723160/22841767/c770fbd0-efa0-11e6-80cb-87572973fcf1.png)

Similar issue to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1643

**Comment by milesap** [comment] 2017-02-24 18:41
Duplicate of #1637

**Comment by IsabellaPan** [comment] 2017-03-07 14:55
Mar 6 2017
Not working yet, in build http://fgpv.cloudapp.net/demo/v1.6.0-0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley

@milesap https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1637 is about Missing Symbology, and this one is for Zoom To Feature button (symbology not missing). Do you consider them to be the same?

**Comment by milesap** [comment] 2017-03-07 15:16
Sorry, looks like I mislabeled the two issues. This one is still an open PR #1721.

#1637 is a no fix since "technically" it is the correct behavior (see @james-rae comment).

**Closed** 2017-03-20 14:53 UTC
Labels: priority: medium, problem: bug
