### ISSUE TITLE
WCAG 2.0 - Keyboard navigation issue

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3822] opened 2020-02-26 13:41 UTC
- Use keyboard to tab through page
- Select Enter to go into the map when get there
- Tab around Map
- Press ESC+Tab at the same time to exit map
- Tab through screen till back at map
- Click Enter to get back into map
- Hit tab to navigate within map

Expected Result: Can navigate in Map and would have to hit ESC+Tab again to leave map
Actual Result: Tab right out with tab. Map is no longer keyboard accessible

**Comment by milespetrov** [comment] 2020-03-05 15:22
First some bad news:

> I don't have a solution for this yet. 

Some more bad news:

> Focus manager is even more complex than I remember it being with the introduction of a second "internal" focus manager (?). 

Some good news:

> I haven't given up entirely, yet.

What was checked/is working as intended:

- [x] Check `esc` + `tab` properly deactivates the FM from viewer
- [x] Check tab back to viewer properly sets `WAITING` and `ACTIVE` statuses as appropriate
- [x] Check that a viewer which has been activated a second time is treated in the same way
- [x] Reset the focus history when deactivating the viewer

Next steps:

Profile the more complex internal parts (*shudders*) dealing with forward focus selection to hopefully see why its not moving focus on viewer components.

**Comment by jolevesq** [comment] 2020-03-31 15:24
@milespetrov do we have progress on this?

**Comment by milespetrov** [comment] 2020-04-14 14:08
No, sorry @jolevesq I haven't had time to dig deeper into this issue. This bug also behaves differently across browsers, FireFox seems to be fine while Chrome has issues.

**Comment by jolevesq** [comment] 2020-04-14 14:24
I know James wanted to release a new version with the few issues we still have. Can this be place inside as well? I understand it looks like complicated to solve but it may be a huge problem for our WCAG compliance. Can you give us an estimate so I can tell the client when to expect a solution. Thanks!

**Comment by jolevesq** [comment] 2020-10-06 17:32
There is a new problem wit the Focus manager. 

Tab around thePage

- Expected result: Can Skip the Map with Tab

- Actual Result: Goes through map layers while repeating the popup for skip or enter

**Comment by spencerwahl** [comment] 2020-11-24 15:01
After https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3852 :

Skipping past the map seems to always be fine now.

The bug in the opening comment still seems to be present;
- Tab to map
- Press 'enter'
- map interaction or not
- Press 'esc+tab'
- tab back around and go back to map
- Press 'enter'

The final step does not allow you to interact with RAMP as it should.

**Comment by milespetrov** [comment] 2020-12-30 14:39
Issue is resolved with merged PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3853

**Closed** 2021-02-05 14:59 UTC
Labels: bug-type: broken use case, priority: urgent, problem: bug
