### ISSUE TITLE
Grid tab order gets stuck with small grid

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1636] opened 2017-01-26 20:19 UTC
To reproduce:

* Open `index-fgp-en.html` with no layers
* Load `happy.json`, which has 3 features
* Open the grid
* Get focus into the grid
* Mash tab key
* Eventually the focus will just go back and forth between the Close Button `X` and the Menu Button `Vertical Ellipsis`

**Comment by milesap** [comment] 2017-02-21 19:17
Is this strictly related to the speed at which the tab key is pressed? If so, we may want to debounce the key press.

**Comment by AleksueiR** [comment] 2017-08-17 12:45
Might be related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2324.

**Comment by JahidAhmed** [comment] 2017-08-18 12:46
@milesap It doesn't seem like it's related to the speed, the issue is occurring on my machine at any speed.

There seems to be a lot of inconsistent behaviour for this specific issue though.

**Comment by JahidAhmed** [comment] 2017-08-18 15:47
The problem seems to be occurring like this (inside `focus-manager.js`):
- `noSourceLink()` is called.
- Then `lastVisibleHistoryElement()` is called.
- That uses the `history` array which is causing this the following ...

2 cases:
1. When it works: `history.slice().reverse()` has the body button of the layer thats datatable is opened in the first position.
2. When it doesn't work: `history.slice().reverse()` has the close button of the actual datatable that's open in the first position.

So, in the first case, the body button is focusable (from `elemIsFocusable()`) and we get expected behaviour.
In the second case, there's is no body button, so the close button is focusable and is causing problems further down the chain when we add items to our linked list.

**Comment by milesap** [comment] 2017-08-18 17:16
Does this occur only when the table is opened through the ellipses menu? I can reproduce if I open that way but not if I open by hitting enter when the layer is selected.

**Comment by JahidAhmed** [comment] 2017-08-18 17:18
Happening in both cases on my machine.

**Comment by milesap** [comment] 2017-08-18 17:53
Problem will happen when this:
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/ui/table/table-default.directive.js#L577

triggers before this:
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/core/displaymanager.service.js#L112

which should hopefully explain why I could reproduce some of the time, all other things being equal.  Let me know if this is a dead end.

**Comment by JahidAhmed** [comment] 2017-08-22 14:35
The line of code in `displayamanger.service` is triggering before the one in `table-default.directive` and the error still seems to be occurring on my machine.

**Comment by milesap** [comment] 2017-08-23 16:01
If you remove the line in `table-default.directive.js` can you still replicate?

**Comment by JahidAhmed** [comment] 2017-08-23 16:06
Oh yeah you're right, I'm not able to replicate it anymore. The link is being created by the last focusable element (close button) and the search bar in the table in that case which is what we don't want.

**Comment by milesap** [comment] 2017-08-23 17:25
A good way to solve this would be to explicitly link the two elements. Instead of 

```js
$.link($rootElement.find(`[rv-state="${panelName}"]`))` 
```

you would do this 

```js
$('the panel close button').link($rootElement.find(`[rv-state="${panelName}"]`))
```

**Comment by JahidAhmed** [comment] 2017-08-23 18:29
If we explicitly set the link between the two elements, we would need to set it between the element that opens the datatable (the rv-body-button in most cases) and the table element itself.

However, I'm not sure if there is a way to know which button was clicked to open the datatable when creating the link in `displaymanager.service`.

Also, if there is a way and we explicitly set the link between these two elements, then if we open the datatable from the ellipsis menu and close it, the focus will (I think?) go back to the body button instead of the ellipses.

**Comment by AleksueiR** [comment] 2017-08-23 18:31
Potentially, maybe, in the future :), the datatable can be opened through an API call as well.

**Comment by milesap** [comment] 2017-08-24 11:00
You would:

1. Move focus to table close button
2. Link the two elements together

As for knowing the source element - a small modification to display manager or its invoking code should make that possible.

**Closed** 2018-05-11 19:46 UTC
Labels: bug-type: unexpected behavior, priority: low, problem: bug
