### ISSUE TITLE
bug(ui): zoom to feature from datatable blanks out overview map

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#371] opened 2016-03-04 14:43 UTC
Steps:
1. Load viewer; ensure overview map is working 
2. Open TOC
3. Open datatable panel for a layer with some data
4. Click on any row; see the map zoom
5. Close datatable panel
6. Observe the overview map is blank now.

The overview map is restored after you manually or zoom the map.

**Comment by mweech** [comment] 2016-04-15 19:19
Could not reproduce.  May have been fixed with the basemap loading as Dynamic layer fix.

**Closed by mweech** 2016-04-15 19:19 UTC
Labels: bug-type: broken use case, experience: ux, priority: low, problem: bug
