### ISSUE TITLE
Datagrid breaks if rapidly opened and closed

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#896] opened 2016-07-14 16:50 UTC
![image](https://cloud.githubusercontent.com/assets/8732588/16847436/1373e192-49bf-11e6-93d5-4cb6d3d5e15d.png)

![image](https://cloud.githubusercontent.com/assets/8732588/16847451/220d6174-49bf-11e6-8d0d-9289bd0870d9.png)

**Comment by AleksueiR** [comment] 2016-07-14 17:55
Duplicate of #893.

**Closed** 2016-09-16 18:17 UTC
Labels: bug-type: unexpected behavior, priority: medium, problem: bug
