### ISSUE TITLE
Filter by Extent icon not appearing in Layer Panel

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2512] opened 2017-12-06 16:28 UTC
Tested build: http://fgpv.cloudapp.net/demo/v2.2.0-daily10/dev/samples/index-fgp-en.html?keys=ZoomScale,JOSM,EcoAction

"Filter by Extent" icon is expected to appear against the layer name in the layer panel once it is enabled under datagrid. Icon is missing even after enabling it. Please investigate

![image](https://user-images.githubusercontent.com/18539315/33672473-47451dd8-da78-11e7-9ded-e2dfb7406f5d.png)

**Comment by JahidAhmed** [comment] 2017-12-06 16:30
Duplicate of #2427 I think: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2427#issuecomment-340447123

**Comment by bkutty** [comment] 2017-12-06 16:34
Thanks. Thought this was fixed

**Closed** 2017-12-11 16:42 UTC
Labels: bug-type: regression
