### ISSUE TITLE
Data Table (for scale dependency layers) - Column Headings frozen when moving scroll bar 

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2081] opened 2017-06-29 18:55 UTC
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily10/prod/samples/index-samples.html
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

- Added above test data to the build by selecting Ozone layer
- Open data table for zoom level 1 which is visible on the map
- Scroll and observe that column headings not moving together with data

This leads the data look like not aligned with column heads.
![image](https://user-images.githubusercontent.com/18723160/27704995-71435c56-5cda-11e7-93e3-7971796ce801.png)

**Comment by milesap** [comment] 2017-07-07 15:19
I can reproduce this on Chrome but not FF. No one else can reproduce this issue in chrome. I'm having issues with chrome lately so this may well be isolated. Please re-test.

**Comment by milesap** [comment] 2017-07-19 11:32
Also fixed on PR #2149

**Comment by milesap** [comment] 2017-07-20 17:21
It's back!

**Comment by AleksueiR** [comment] 2017-08-02 16:57
Seems to be fixed by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2222 or https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2271.

**Closed** 2018-01-25 20:49 UTC
Labels: bug-type: unexpected behavior, priority: medium, problem: bug
