### ISSUE TITLE
Transparency - Dynamic Layer - Dynamic Legend? - bug from 1.7 forwards

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#2528] opened 2017-12-18 16:34 UTC
The transparency for services added as Dynamic Layers is behaving oddly from about FGPV 1.7 forwards (tested on 1.7.0 , 2.0.0 and 2.1.0 with problem; whereas when tested on FGPV 1.5.1 it works correctly).

The behavior seen is that when transparency is altered the colors fade but the layer does not allow things underneath to be seen through it.  

The service tested is this one:
http://webservices.maps.canada.ca/arcgis/rest/services/INAC/community_well_being_index_2011_en/MapServer

which has Dynamic Legend enabled. 

This is what the layer should look like with transparency:
![image](https://user-images.githubusercontent.com/5502696/34116399-86e6230c-e3e6-11e7-968b-af18e3c851dd.png)

But looks like this instead:
![image](https://user-images.githubusercontent.com/5502696/34116422-977ca740-e3e6-11e7-8ac1-9935206653ce.png)

Most if not all of the services created using the FGP-DDR have Dynamic Legend enabled.

@yblain @phuppe

**Comment by james-rae** [comment] 2017-12-28 19:07
I get the same failing behavior on v1.5.1 (using [this sample](http://fgpv.cloudapp.net/demo/v1.5.1/prod/samples/index-fgp-en.html))

Changing opacity at the top-most level (layer level) will adjust the overall layer image client-side (CSS I suppose), which works. Changing at a child layer lever will give the "transparent against solid white" look shown above.

I dug more into it, it seems the issue is caused by Dynamic Layers having a default image format of `png8`, which will support transparency but only in the sense of a pixel is totally transparent, or totally opaque. This is what's causing the faded white look of child opacity.  If I change the default to `png32`, we get a full alpha spectrum on the image, allowing the desired results.

I did a quick test, the geoApi code is in this commit https://github.com/james-rae/geoApi/commit/79b520ab57e7b3116c9c3be23c3a4de56da6e1bc .  However I noticed there were some issues with how the controls on the UI were behaving. E.g. change child opacity (things ok), then change top level opacity. The layer will go full opaque and certain sliders will no longer affect transparency.  Needs more debugging to know if it's geoApi or the control bindings.

`png32` should be a safe default, as that is the format that ArcMap uses when consuming a map service.  It will increase the file size of the images being served.

Thoughts?

**Comment by james-rae** [comment] 2017-12-28 19:35
Also, more investigation with @AleksueiR  , appears the top-level opacity slider for dynamics is broken at version 2 and up.

Will do a bit more poking around to narrow down the cause of that.

**Comment by james-rae** [comment] 2017-12-28 20:18
Top-level opacity slider fixed by doing this https://github.com/james-rae/geoApi/commit/2f210f684304d555f7cb5005d17a3847e6d1d73f

Pre- v2, all the child opacity updates would be collected and applied at once. In v2+, each is being hit individually. The way the new value was handed to the ESRI API caused the other children to be erased. Problem wouldn't affect single child layers, or the last child of a set.  Above fix changes the approach to preserve all values.

If we are ok adopting `png32`, this is probably ready to go, fixing broken top-level slider and washed-out child level opacity.

**Comment by james-rae** [comment] 2018-01-02 18:41
Did some tests using the layer at the top of this issue.  The Point view is the default Canada extent. The Polygon view is GeoSearching to Winnipeg, then two zoom levels out.  The point image is considerably more complex / detailed than the polygon one.

Image Format | Geometry | Opacity | File Size
------------ | ------------- | ------------- | -------------
PNG8 | Points | 100 | 70KB
PNG8 | Points | 50 | 62KB
PNG8 | Polygons | 100 | 17KB
PNG8 | Polygons | 50 | 17KB
PNG32 | Points | 100 | 274KB
PNG32 | Points | 50 | 266KB
PNG32 | Polygons | 100 | 21KB
PNG32 | Polygons | 50 | 21KB


From this test, the size of the simpler images increased by a factor of ~1.25. The complex images by a factor of ~4

**Comment by james-rae** [comment] 2018-01-03 13:54
Worth noting, the x4 factor should be worst case (8 x 4 = 32).  The improvements in the polygon layer are likely due to optimizations in the PNG compression (the polys have big swaths of identical pixels).

**Comment by mweech** [comment] 2018-01-03 17:53
so this has nothing to do with density of features and everything to do with the detail level of the symbols it is rendering? i.e. a layer of points with simple mono shaded circles would not increase as dramatically compared to fancy icons?

**Comment by james-rae** [comment] 2018-01-03 18:22
Yes, though increased density can increase complexity due to overlapping.  Circles become crescents of varying size, for example.

As well, a small mono circle is still relatively complex just because you have to encode the border.  But yes, you would likely get compression gains for the mono middle (compared against a complex bitmap image icon, for example). 

Without doing more research / test cases, I'd say the image size approaches x4 as we get away from basic images (shapes that work well with [PNG compression](https://en.wikipedia.org/wiki/DEFLATE), like big mono-coloured polygon swaths).

Alex also made a suggestion that we could add the image type to the config schema. Default to PNG32 (as it is functionally correct), but allow other things to be chosen if performance is a concern. We could spin this off to a different issue if we want.  Would require more work to allow support for this via RCS and Add Layer button.

**Comment by james-rae** [comment] 2018-01-16 21:14
Decision was to add image format to the Dynamic Layer config node in RAMP. Default will be `png32` to provide best experience, implementer can change to other supported formats if they need something different or more lightweight.

**Comment by YaroRoodzit** [comment] 2018-04-12 20:40
Tested on Chrome and IE.Transparency change working properly.

**Closed** 2018-05-01 19:40 UTC
Labels: bug-type: regression, bug-type: unexpected behavior, priority: high, problem: bug
