### ISSUE TITLE
Map stuck in a loading state if rv-wait is set to true

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3207] opened 2019-01-02 15:41 UTC
If `rv-wait` is set to `true` then the map gets stuck in a loading state. Specifically the issue is [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3/src/app/core/core.run.js#L46) where a lack of an `events.rvBookmarkInit` event fails to trigger an `events.rvReady` event. 

It seems this event should trigger given a `rv-restore-bookmark` attribute on the root element. `rvBookmarkInit` is emitted in https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3/src/app/core/reload.service.js#L112 but this function is never called.

Broken: http://fgpv.cloudapp.net/demo/v3/dev/samples/index-enhanced-table.html
Working (since `rv-wait` is not on root element): http://fgpv.cloudapp.net/demo/v3/dev/samples/index-samples.html

Issue seems to be missing logic for detecting an `rv-restore-bookmark` attribute and passing this to the reload service. I'll defer to the bookmarking expert @spencerwahl

**Comment by spencerwahl** [comment] 2019-01-07 17:35
`rv-restore-bookmark` is no longer functional it seems, not due to a bug... there is just no code for it that I can find.

Fixed by calling initialBookmark in `index-enhanced-table`.

**Closed** 2019-02-25 19:55 UTC
Labels: bug-type: unexpected behavior, needs: estimate

**Comment by spencerwahl** [comment] 2019-02-25 20:00
Confirmed non-functional, removing its reference in the docs. Commit is in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3310
