### ISSUE TITLE
Expand layers not working after removed one sub-layer and then applied "Back To Cart" 

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1611] opened 2017-01-20 16:20 UTC
Tested build http://fgpv.cloudapp.net/demo/v1.5.0-14/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley

-  Removed one sub-layer for any layers with multiple sub-layers, for example Mercury emissions sub-layer under CESI: Other Air Indicators
-  Click "Back to Cart"
-  Click Expand Groups to expand all layers

No sub-layer displayed under CESI: Other Air Indicators, even the chevron is in expand status.

![image](https://cloud.githubusercontent.com/assets/18723160/22156637/361e2cce-df02-11e6-8595-61244abcb2bf.png)

**Comment by james-rae** [comment] 2017-01-20 21:40
Caused by problem with how `angular.merge` is handling RCS layers with modified guts.  As an aside, is the ability to remove children of dynamic layers a new feature??

The error is `Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed.`

The culprit is function [addRcsConfigs](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.5.0-14/src/app/core/bookmark.service.js#L720). Error flow is roughly the following.

* Site loads with an RCS Based Dynamic Layer that has multiple child layers. Will use two in our example, with indexes `1` and `2`.
* User removes the first child layer, index `1`
* User creates a bookmark (or uses back to cart, which generates a bookmark behind the scenes).
* The bookmark indicates we have the RCS layer, and it only has child array with one layer, layer `2`.
* Site reloads and begins bookmark parsing. Bookmark is properly decoded and a config snippet is generated. It has the `layerEntries` array having one object, targeting layer `2`
* Function `addRcsConfigs` starts.
* It downloads the config snippet for our layer from RCS (`configService.rcsAddKeys(...)`). This snippet will be in the original form, and `layerEntries` array will have two objects, targeting in order, layer `1` and `2`.
* It then does an `angular.merge` on the original RCS snippet and the bookmark snippet.  The resulting `layerEntries` array has two objects, targeting layer `2` and `2`.
* This creates a duplicate, and eventually causes the there error in the angular repeater.


You can test / trigger the issue with the following bookmarks (you can copy the `rv=...` content to your local builds).  You can also load rcs layer `?keys=CESI_Other` to get a simple original state.

Good bookmark - loads CESI other with both children
http://fgpv.cloudapp.net/demo/v1.5.0-14/prod/samples/index-fgp-en.html?rv=B,YmFzZU5yQ2FuMA,NDM0MDE3LjU,MTI5OTM3Ni40OTk5OTk5OTk4,MTc1MDAwMDA,M2M5MjAyYzljMDg4YzljMDkwcmNzLkNFU0lfT3RoZXIuZW4

Bad bookmark - loads CESI other with first child removed
http://fgpv.cloudapp.net/demo/v1.5.0-14/prod/samples/index-fgp-en.html?rv=B,YmFzZU5yQ2FuMA,NDM0MDE3LjU,MTI5OTM3Ni40OTk5OTk5OTk4,MTc1MDAwMDA,M2M5MjAxYzljMDkwcmNzLkNFU0lfT3RoZXIuZW4

**Comment by james-rae** [comment] 2017-01-26 21:26
Note a secondary issue was found while fixing this.  Will resolve after legend refactor.
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1640

**Closed** 2017-02-09 16:16 UTC
Labels: bug-type: unexpected behavior, problem: bug

**Comment by IsabellaPan** [comment] 2017-02-13 19:15
Feb 13 2017
Fixed. Verified with build http://fgpv.cloudapp.net/demo/v1.5.0/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
