### ISSUE TITLE
Overview map open/close toggle is unclickable

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#2692] opened 2018-05-01 20:51 UTC
Clicking on the overview map toggle icon _does not_ open/close the map. Clicking a few pixels to the right of the overview map _does_ open/close the map. Icon looks to be at wrong z index level.

![overviewmap](https://user-images.githubusercontent.com/2006029/39493065-89c6a4c4-4d5f-11e8-9275-a462292e05f5.gif)

**Comment by AleksueiR** [comment] 2018-05-02 11:26
The container for the map controls (zoom in/out) stretches up to the top edge of the map container and covers the overview map's close button making it unclickable.

Duplicate of #2642.

**Comment by YaroRoodzit** [comment] 2018-05-31 20:00
Tested with /v2.4.0-b1. Issue resolved.

**Closed** 2018-06-20 18:55 UTC
Labels: bug-type: unexpected behavior, priority: high, problem: bug
