### ISSUE TITLE
"Zoom To Feature" not working for Land Pub Standard Zone layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#695] opened 2016-05-31 19:55 UTC
Tested on build: http://fgpv.cloudapp.net/demo/v0.16.0/index-one.html  for IE11, Chrome & Firefox
"Zoom To Feature" not responding for Land Pub Standard Zone layer. Steps:
- Click Legend icon to display all layers
- Click Land Pub Standard Zone to open Data Table for this layer
- Click "Zoom To Feature" button for any map point as highlighted in below screenshot

![image](https://cloud.githubusercontent.com/assets/18723160/15688186/cc8bdcca-2746-11e6-96cd-052ab8f78295.png)

**Comment by mweech** [comment] 2016-06-01 18:46
This bug is a duplicate of #616 due to this layer using a custom projection.

**Closed by mweech** 2016-06-01 18:46 UTC
Labels: problem: bug
