### ISSUE TITLE
Users are Unable to Close Point Information Box

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1431] opened 2016-11-28 15:31 UTC
**Usability Issue:**

V13. Unable to close point information box (Type: Design)

Once the point information box appeared testerswere unable to close it.  They would flipback and forth between the legend and the point information.  They also tried clicking on the map but thatdidn’t close it either.  Most testers did not see the “X” to close the point information box without assistance.

**Comment by AleksueiR** [comment] 2016-12-05 12:56
### V13
By design; no fix needed.
- The point information panel should not be closed by clicking on the legend icon in the app bar - it needs to stay open when switching between it and the legend, so it's possible to modify the view of the map and not lose the feature details the user is interested in.
- The point information panel should not be close by clicking on the point information icon in the app bar, as this breaks consistency in behaviour of the app (the legend cannot be closed by clicking on the legend icon).
- The point information panel should not be closed by clicking on the map. Clicking on the map will open the point information panel or update its content if opened already.

Right now there is a bug that closes the point information panel when clicking on its icon in the appbar: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1399

**Comment by mweech** [comment] 2016-12-09 15:34
As per review of Usability items with FGP team, will look at having the "close" and "expand" buttons on feature information detail panel be in a single row at the top of the panel (above Feature title)

**Comment by AleksueiR** [comment] 2016-12-12 17:45
Floating header is removed; `close` and `expand` buttons are added to the same line as the layer name (layer name will be truncated if too long). The header stays in place as the content can be scrolled.


![](https://i.imgur.com/QCeHIJ7.png)
![](https://i.imgur.com/51Ty7gY.png)
![](https://i.imgur.com/H9pRjX2.png)
![](https://i.imgur.com/YBel95w.png)

**Closed** 2017-01-10 14:33 UTC
Labels: addition: change request, priority: high
