### ISSUE TITLE
Details expand is blank for custom details panel

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3888] opened 2021-04-26 12:32 UTC
When we use a custom details panel and we click on expand, it doesn't take the content of the panel but what is inside element attribute. The result is a blank age if element attributes are empty. Expand should use the panel content to render itself.

![image.png](https://images.zenhubusercontent.com/5695178c638e718c99600115/c355abc5-4d9b-424a-a9f4-a812f52792d8)

**Comment by milespetrov** [comment] 2021-04-27 17:41
Thanks for the :bug: report! To make this easier to test and fix can you provide a branch we can pull (and any extra steps needed to reproduce this issue)? You said this occurs on custom detail panels, I'm not sure if there is one already on our sample page http://fgpv-app.azureedge.net/demo/branches/develop/dist/samples/index-samples.html. If there is a sample config with a custom detail panel then the sample # would work too.

Thanks you!

**Comment by james-rae** [comment] 2021-04-28 14:50
@milespetrov Sample 68 has custom details templates, but they do not have the "expand" option. So agree we would need to see what is being done to set up the custom details in this case (the screenshot looks like the standards details list so might be something different going on).

**Comment by jolevesq** [comment] 2021-05-18 11:50
Hi @james-rae! Is this can be part of 3.3.4?

**Comment by james-rae** [comment] 2021-05-18 12:55
Hi @jolevesq , please see the above comments and provide us some details/samples. We cannot reproduce on our end at the moment.

**Comment by jolevesq** [comment] 2021-05-18 14:05
@james-rae When we use the sample http://fgpv-app.azureedge.net/demo/tags/v3.2.0/dev/samples/index-samples.html?sample=68 it always work but I don't know if it is because there is always more then one element in the detail panel.

If you use this link https://jolevesq.github.io/contributed-plugins/chart/samples/chart-index.html?sample=1 and click on a point in the center row, the details panel will open and there is only one element. If the expand is click, the content of the expand window will be the attribute, not the details template.

**Comment by james-rae** [comment] 2021-05-18 15:37
Looking at the [config file](https://github.com/jolevesq/contributed-plugins/blob/gh-pages/chart/samples/chart-pie-config.json) for that sample, I can see one layer has a `details` element but the properties inside appear to be custom. The only properties the ramp schema supports is `template` and `parser`, so I'm not surprised your `value` string is being ignored...I don't think there is any code in RAMP looking for that property.

Let me know if there is some additional stuff going on in your sample/plugin that I'm missing.

**Comment by jolevesq** [comment] 2021-05-18 17:32
For this sample, I modify the content of details panel on opening. I think the expand button should use the content of the details panel window, but it doesn't.

You can try with this as well:

- Go to https://osdp-psdo.canada.ca/en/osdp/explore
- Search for Roberts Bank
- Click map area button on the first element
- Click on an item of the BC Major project inventory
- When click on expand (single element), the content is blank.

This layer is loaded from RCS and I use code to add configuration:
```
 // if BC layer added automatically, set template and parser
if (layer.id.contains('ea4c0bdb-a63f-49a4-b14a-09c1560aad0b')) {
   layer._viewerLayer.config._details = { parser: "templates/wms-bc-script.js", template: "templates/wms-bc-template.html" };
    layer._viewerLayer.config._featureInfoMimeType = "text/html";
}
```

It works, I am able to to use the custom details info but when we expand I get a blank page.

**Comment by jolevesq** [comment] 2021-06-04 14:24
@dan-bowerman Hi, can this be part of 3.3.4 as well?

**Comment by yileifeng** [comment] 2021-06-21 19:37
Hi @jolevesq, this [PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3948) has been opened to address the empty details page for the wms-bc templating that you mentioned. 

As for the custom plugins sample page you linked, perhaps using the RAMP schema options (`template` and `parser` under the `details` section) rather than the `value` property used in that sample page might fix the problem (converting the current `md` format to `html`) as this is the intended method to support custom details templates. 

Currently when expanding the details panel, it will detect if there is a `details.template` provided via config and compile that as a custom template or it defaults to the element attributes otherwise.

**Comment by jolevesq** [comment] 2021-07-05 12:54
Hi @yileifeng from the code snippet I showed, I thought I used the details section (parser and template) with the template as html. You mean the OSDP platform has not implemented it the same I did?

**Comment by yileifeng** [comment] 2021-07-05 13:58
Hi @jolevesq, I was referring to the contributed plugins sample page you linked: https://jolevesq.github.io/contributed-plugins/chart/samples/chart-index.html?sample=1 which contains the following config snippet under the details section (no usage of parser or template): 
```
"details": {
    "enabled": true,
    "value": "## What a nice pie chart\n**Useful data listed below**\n * Label field value: {{label}}\n * Data: {{data}}\n\n\n![sd-logo](https://raw.githubusercontent.com/showdownjs/logo/master/dist/logo.readme.png 'sd logo')\n\n[Get Showdown!](https://github.com/showdownjs/showdown)"
 }
```
As for the OSDP issue, that should be fixed in the next release with the PR linked above.

**Closed** 2021-07-16 17:17 UTC
Labels: bug-type: confusing, for: FGP, priority: urgent, type: corrective
