### ISSUE TITLE
Symbology Stack Toggles and Datagrid CESI Bug

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3045] opened 2018-09-26 16:22 UTC
Steps to Reproduce: 

http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html?keys=CESI_Other

## Part 1a)
![capture](https://user-images.githubusercontent.com/25359812/46092828-bf59a580-c183-11e8-9724-a2c987fabae2.PNG)

Toggle off "Greenhouse gas emission.." layer entirely. You will see points remaining on the map from "Mercury emissions to air.." Open the "Mercury emission..." datagrid. 0 entries are shown.

**Expected behaviour:** 
- points that are toggled on for "Mercury emission..."  should show up in the datagrid (it should not be empty)
 

## Part 1b)

Working from the state pictured above, toggle off and on a button in the Mercury stack. The datatable will go back to normal:

![capture](https://user-images.githubusercontent.com/25359812/46093958-bcac7f80-c186-11e8-81d4-dc587cb032f8.PNG)

**Expected behaviour:** 
- as per expected behaviour for 1a) toggle button in "Mercury emission..." stack should not have to be the one to trigger the expected behaviour for the datagrid
 

## Part 2
Also issue weirdly doesn't happen if Greenhouse gas emissions is toggled off, but all symbologies in its stack are toggled on:

![capture](https://user-images.githubusercontent.com/25359812/46093726-16607a00-c186-11e8-831a-a69bed6c91c9.PNG)

**Comment by JahidAhmed** [comment] 2018-09-26 16:34
Also worth noting that after completing `Part 1b)` mentioned above, if you try to open the datatable for GHG emissions, it will show all its entries even though the symbologies are toggled off. This can then be fixed by repeating `Part 1b)` but for this layer (which causes a loop where the first child breaks)

**Comment by dane-thomas** [comment] 2018-09-26 18:37
Another thing to note is if you open the datatable for "Mercury emissions to air.." and toggle the symbology for "Greenhouse gas emission..", the table gets filtered as if you were toggling the symbology for "Mercury emissions to air.."

**Comment by AleksueiR** [comment] 2018-09-26 18:42
@ShrutiVellanki Could you please also describe expected behaviours for sections 1a) and 1b), for clarity?

**Comment by ShrutiVellanki** [comment] 2018-09-26 18:49
@dane-thomas 
> Another thing to note is if you open the datatable for "Mercury emissions to air.." and toggle the symbology for "Greenhouse gas emission..", the table gets filtered as if you were toggling the symbology for "Mercury emissions to air.."

Good point, it might have something to do with this Edge case: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3019 possibly? As in both layers share the same symbologies so it might not be differentiating them somewhere in the datagrid code

@AleksueiR done

**Comment by dane-thomas** [comment] 2018-09-27 18:11
Upon investigation, it appears that the definition clause for dynamic layers is being stored on the parent `DynamicRecord` without a reference to the child the clause applies to. This would explain why changing the symbology toggles on one child effects the datatable of the others. 

Interestingly, this bug only seems to be effecting the results in the datatable and not the actual points on the map so we may be able apply the logic used for the map points to the datatable filter as well.

**Closed** 2019-05-31 18:28 UTC
Labels: bug-type: confusing, problem: bug
