### ISSUE TITLE
Get Link - Group Layer Visibility Not Persisting

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#824] opened 2016-06-23 19:15 UTC
Visibility for below four highlighted layers are not captured while using Get Link URL. These layers re-appeared on the Get Link map.
![image](https://cloud.githubusercontent.com/assets/18723160/16316441/a5cdf7a6-3954-11e6-9d27-be5068e7e5d5.png)

Comparing with original map, all layers under Legend were hidden.
![image](https://cloud.githubusercontent.com/assets/18723160/16316521/f387aabe-3954-11e6-9c1d-ad1768812159.png)
- [x] Encode info for child layers
- [x] Update bookmark version
- [x] Parse child info, convert to `layerEntries` config elements
- [x] Store `100` opacity as `99` to save space
- [x] Refactor decoder due to maximum statement RULES
- [x] Update decoder page to support new format
- [x] Remove null flagging logic of original fix
- [x] Fix setting of query flag from config file, which wasnt working to begin with

**Comment by spencerwahl** [comment] 2016-06-24 17:40
Cause:
Bookmark captures state for the top level only, it seems like the visibility set on the top level isnt being applied to children.

Possible solutions:

1. track state for sublayers (this uses a lot of bookmark real estate)
2.  track only visibility for sublayers (this is probably just as expensive as the first option)
3.  force all sublayers/groups to off when top layer is turned off (how the control works)

3 would be my choice, the layer would only be invisible in the original map if all sublayers were turned off. Downside being that defaults stay for sublayers if the top level is visible.

**Comment by milesap** [comment] 2016-09-16 11:18
Just to clarify what solution was chosen here - it was option 3 'force all sublayers/groups to off when top layer is turned off (how the control works)'. If the top level is hidden, all descendants are hidden as well. No changes are made to descendants when the top level is visible.

**Comment by james-rae** [comment] 2016-09-21 20:13
Issue re-opened to attempt to preserve child information in the bookmark.

**Comment by james-rae** [comment] 2016-09-21 20:58
# Issue with Autogenerated Child Layers

## Example Service

* Creatures [0]
  * Frogs [1]
  * Snakes [2]
* Swamps [3]

## Dynamic Layer Config Structure

We can specify which sub-layer indexes to include in our layer.  By convention, if a sub-layer has children, they are added to the on-screen legend by the legend engine.  As an example, config setting `layerEntries: [{index: 0}, {index: 3}]` will make a legend that looks just like the service definition above.  

But a setting of `layerEntries: [{index: 1}, {index: 3}]` will create a legend that looks like

* Frogs
* Swamps

In the current config schema, there is no way to specify details about auto-included children of sub-layers.  I.e. If I want the Creatures structure, and want Frogs to have visibility turned off at the start, I can't say something like `layerEntries: [{index: 0, visibleChildren:[2]}]`

## The Problem

When the legend generates entries for children (specifically ones not explicitly specified in the config), the user can then change settings on those layers.  We want those changes to be preserved in the bookmark.

When a bookmark is consumed by the app, it works by modifying the config file before the app consumes it.  The file gets tweaked to resemble the state the app was in when the bookmark was generated.

So when information about auto-generated children come in on the bookmark, we have no way of encoding that in the config file and still have the legend structure look the same.

Example:  Starting config of `layerEntries: [{index: 0}, {index: 3}]` (which gives us a nested legend that looks like the service structure), user has changed visibility on Snakes layer (index 2).  If we add that to the config during bookmark restore -- `layerEntries: [{index: 0}, {index: 2, visibility: {value: false}}, {index: 3}]` , we get a legend of

* Creatures
  * Frogs
  * Snakes
* Snakes (visibility off)
* Swamps

## Possible Solution 1

When parsing the bookmark, we analyse the indexes on the bookmark and compare to the indexes of the original config file.  If we have indexes that are not in the original file, we store those somewhere else, and don't insert them in the config.

When the legend is being auto-generated, we need to check our bookmark stash for extra information (e.g. a changed visibility setting) and apply it then.

Main appeal: The config schema is left alone.
Main drawback: The bookmark is now impacting the legend generation module, which happens post-load.  The current architecture where the bookmark modifies the config file and quits is much cleaner.

## Possible Solution 2

We modify the config schema to allow child settings to be specified. Currently, we would need to track `visibility`, `queryable`, and `opacity`.

Main appeal: Bookmark can now update the config file and be done.
Main drawback: Config schema update, one that could be considered overly complex for a single use case.

## Possible Solution 3

Lazy James. Legends from a bookmark look different than the original state.  Even Lazy James thinks this is rather lousy.

**Comment by milesap** [comment] 2016-09-22 11:39
I vote for solution 1 :+1: 

My 1/2 cent: it might make sense for the parent to store this extra information - which is included in the bookmark url. The legend can then apply the settings post-load so that bookmark doesn't get tangled with that responsibility.

**Comment by AleksueiR** [comment] 2016-09-22 11:50
My vote:
```js
return solution_2 === 'lot\'s of work' ? solution_3 : solution_2;
```

I think a bookmark should not have more power in terms of configuring the viewer than a config. If someone wants to recreate a bookmarked state in a config, they should be able to do that. With __Solution 1__ it's not possible and - as James said - it would also required bookmark specific changes to the legend module.

**Comment by milesap** [comment] 2016-09-22 12:27
I'm wondering if most bookmarking users will have access to change the config. If they do, would a new map need to be created (with the proposed config changes) so that their bookmark displays as intended? 

If we go with solution 2 we can consider informing the user that their bookmark contains unsaved layer changes and to update the config file (so they don't think it's a bug).

**Comment by mweech** [comment] 2016-09-22 13:19
Solution 2... We will ultimately have to support child layers in the config anyhow as part of structured legend.  The question is "when?".

Let me know the scope of making this change NOW vs. doing it as part of the upcoming schema refactor for Structured Legends.

**Comment by james-rae** [comment] 2016-09-22 15:24
Summary of in-pod discussion:  Solution 1 shot down as it would mean the bookmark would have more configuration power than the config file, which is not that smart.

Will look at docs for Structured Legend config schema.  If easy to implement into auto-gen legends, will do now, otherwise will accept the limitation and fix when we implement structured legends.

**Comment by james-rae** [comment] 2016-09-23 15:07
Proposed Solution

# Auto-Gen Legend vs Structured Legend

Reviewing the preliminary design docs, structured legends are considerably more complex than the auto-generated dynamic layer case.  The solution will not attempt to merge the two cases into one common code base.  It will, however, attempt to keep the configuration schema for the two cases as similar as possible.

# Config Schema Change

Will add a new property to `dynamicLayerEntryNode` called `children`.  This name was picked to match the [Structured Legend schema proposal](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Config-Schema#structured-legends). It is an array of `dynamicChildOptionNode`, which is a new node, essentially a stripped down version of `dynamicLayerEntryNode`. It has properties `index`, `visibility`, `opacity`, `query` , all which use same definitions as the properties in `dynamicLayerEntryNode`.

This allows us to set initial states on child index of a dynamic layer, but will not cause those children to appear on the root level of the layer in the legend.

Sample (using the swamp service above):

```
layers: [
	{
		id: "swamp",
		name: "Swamp Party",
		layerType: "esriDynamic",
		layerEntries: [
			{
				index: 0,
				children: [
					{
						index: 1,
						visibility: {value: false}
					},
					{
						index: 2,
						query: {value: false}
					},
				]
			},
			{index: 3}	
		],
		url: "http://swampy.org/arcgis/rest/services/swamp/MapServer",
		metadataUrl: "http://swampy.org/enhance/metadata"
    }
]
```

This would give us a legend of

* Creatures
  * Frogs (visibility off)
  * Snakes (identify off)
* Swamps

# Legend Generator

The code that parses `layerEntries` and generates config fragments for the legend items will also parse the children array.  Since the objects share the same properties, they can be used as config fragments in the same way.  It will not trigger the addition of the children to the layer root.

Will also need to update some of the code that bulk-applies properties like visibility to all children.

Future support for Structured Legends will require a different generation routine anyways so these two cases should be isolated.

**Comment by james-rae** [comment] 2016-10-07 21:02
People keep closing this issue :hammer:

**Comment by james-rae** [comment] 2016-10-07 21:05
This was very very underestimated.  Challenges encountered included

* Query flags were broken, requiring an unexpected fix.
* Rules putting a maximum number of lines on functions caused otherwise unnesseccary refactors to bookmark parse function.
* Bookmark parsing logic being split between bookmark module and layer-specific classes made versioning more difficult than it should be.  See discussion issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1265
* Legend generator had a lot of code with assumptions that children would not be set at start time, and would apply defaults from parents. This behaviour had to be conditionally omitted
* Legend generation code in general needed to be learned, as it was critial in both the encoding and decoding of bookmarks.
* Schema change to config to support dynamic child settings, required analysis and messing around with code.

**Comment by james-rae** [comment] 2016-10-27 13:22
Additional slowness due to refactor to the bookmark format that was initially implemented. Some of the refactors were to help accommodate for structured legend and layer/legend class refactors

**Closed** 2017-01-09 20:11 UTC
Labels: bug-type: broken use case, priority: medium, problem: bug
