### ISSUE TITLE
Removed layer reappears after zoom in 

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#772] opened 2016-06-14 12:26 UTC
When we have a loading layer  and we remove it:

<img width="401" alt="screen shot 2016-06-14 at 8 20 48 am" src="https://cloud.githubusercontent.com/assets/3472990/16042503/06232af2-3209-11e6-8e8d-0452fe713b84.png">

<img width="404" alt="screen shot 2016-06-14 at 8 21 18 am" src="https://cloud.githubusercontent.com/assets/3472990/16042519/2078463a-3209-11e6-8585-dc4d7c8c6dff.png">

When we zoom in to the map, the legend is refresh and the deleted layer reappear.

<img width="402" alt="screen shot 2016-06-14 at 8 21 27 am" src="https://cloud.githubusercontent.com/assets/3472990/16042526/2c233526-3209-11e6-8225-0d3a8a85a8cc.png">

**Comment by AleksueiR** [comment] 2016-06-14 12:27
Duplicate of #755 ?

**Comment by jolevesq** [comment] 2016-06-14 17:50
From waht I read no, because the layer is not shown in the legend entry in #755. Maybe to solve will solve the other at the same time. We can say they are related

**Comment by milesap** [comment] 2016-08-12 12:46
Resolved on #985 in PR #1052

**Closed** 2016-08-23 13:52 UTC
Labels: bug-type: unexpected behavior, priority: medium, problem: bug
