### ISSUE TITLE
feat(ui): add support for radio-button style visibility toggles in toc

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#108] opened 2015-12-16 18:46 UTC
As implemented in GcViz. Restricts view of only one layer per group at a time (the group itself still can be turned off by the group toggle though).
Apart from switch logic, need visual clues to indicate linked layers.

**Comment by jolevesq** [comment] 2016-11-23 14:03
In GCViz, we have a border around the group.

**Comment by mweech** [comment] 2017-03-27 13:26
@AleksueiR is this issue a duplicate of a task elsewhere in your thematic map work?

**Comment by AleksueiR** [comment] 2017-05-25 14:41
I think this is original one.

**Closed** 2017-07-26 11:07 UTC
Labels: experience: ux, improvements: enhancement, needs: UX review, v2.0.0
