### ISSUE TITLE
Datatable csv export not formatted properly in iOS devices

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1720] opened 2017-02-23 19:15 UTC
Tested Build :http://fgpv.cloudapp.net/demo/v1.5.1/prod/samples/index-fgp-en.html?keys

CSV export of datatable looks as below.  This is not an issue in Android devices

![image](https://cloud.githubusercontent.com/assets/18539315/23274819/195744d2-f9d2-11e6-9d0d-7d491ab5cb0b.png)

**Comment by milesap** [comment] 2017-02-28 14:21
This issue seems to be with the actual csv generation, not limited to any particular OS. Confirmed same issue in downloaded csv file in excel (just expand the columns). Row breaks seem fine, just word wrapping on smaller viewports. Not sure why some values are duplicated with long white space, though we should first rule out a data issue before I blame DataTables

**Comment by AleksueiR** [comment] 2017-02-28 14:24
I think this is about CSV loading up in the browser instead on iOS devices of being saved as to a file.

**Comment by milesap** [comment] 2017-02-28 14:37
That would imply iOS allows file downloads which it never has. @bkutty Please clarify this issue with additional details on what is being tested and what the expected result should be.

**Comment by bkutty** [comment] 2017-02-28 17:51
Tested Device : 
![image](https://cloud.githubusercontent.com/assets/18539315/23416562/50e1fa72-fdb1-11e6-9eb7-f269bb94630c.png)

**Steps to Reproduce**

Load the FGP site in Safari
Navigate to Layers and select JOSM layer
Select the data table and click "Export"

Export, brings up a csv  directly on the browser. Screenshot is as above.

Is it possible to have this in a more readable format. I am not sure of the user's expectation in this case.

**Comment by AleksueiR** [comment] 2017-02-28 18:49
As Miles mentioned - iOS doesn't not allow saving files. Maybe we can display a warning to iOS users that the CSV export will be opened in the browser?

**Comment by jolevesq** [comment] 2017-04-20 11:53
Now it works on Safari OSX. It does not open it in a new tab anymore. You can download it. Still open in a tab in iOS.

**Comment by mweech** [comment] 2018-12-03 19:32
Expected behavior: File auto downloads in iOS.

**Comment by AleksueiR** [comment] 2019-05-31 15:42
See this FileSaver issue for more details: https://github.com/eligrey/FileSaver.js/issues/375. And especially this comment: https://github.com/eligrey/FileSaver.js/issues/375#issuecomment-408213567

I tried setting the MIME type to `application/octet-stream` and iOS did give me an option to save although I couldn't confirm on BrowserStack that it actually does save. Also, the file comes up as unknown format and without a proper file name:
![](https://i.imgur.com/EvqGB5e.png)

There doesn't seem to be a client-only solution for this problem. People suggest moving this to the server sider.

**Closed** 2021-05-26 12:07 UTC
Labels: bug-type: broken use case, problem: bug, type: corrective
