### ISSUE TITLE
WCAG - More status messages required

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3848] opened 2020-10-29 17:41 UTC
More Status messages need to be addded using ARIA to identify all dynamic content changes made from the map on the page. In a single-page application people who cannot see and use screen readers do not know that content has changed on the same page. E.g., page is updated with search results.

**Comment by milespetrov** [comment] 2020-12-30 14:48
Waiting for feedback on related issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3847

**Comment by dan-bowerman** [comment] 2021-05-26 13:24
As we are pretty certain the cause and solution to this is the same as #3847, I would like to close this one as duplicate, and we will keep track of further discussion and development in #3847.

**Closed by dan-bowerman** 2021-05-26 13:24 UTC
Labels: improvements: quality, priority: urgent, type: corrective
