### ISSUE TITLE
API `MouseMove` endpoint fires continuously on `MouseDown`

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2581] opened 2018-02-12 14:13 UTC
`MouseMove` fires about every second on the same screen point after the `MouseDown` event. See the gif below:

![mouse-move-down](https://user-images.githubusercontent.com/2285779/36100587-c37121c2-0fd4-11e8-9591-60a064499e68.gif)

**Comment by milesap** [comment] 2018-02-15 13:54
Cannot reproduce on `index-samples.html` when entering `RZ.mapInstances[0].mouseMove.subscribe(console.error);`. Working as intended even when holding the left mouse down over a feature.

Please provide any additional steps you took or if I missed something.

**Comment by AleksueiR** [comment] 2018-02-15 18:53
There was a number of changes to develop. I'll rebase the branch CIP uses and see if the issue persists.

**Comment by milesap** [comment] 2018-02-15 19:00
@AleksueiR showed me issue on dev branch, will investigate

**Comment by milesap** [comment] 2018-02-16 12:51
Bug is unconfirmed by the entire team (except Alex - hopefully him as well). Reviewed the [one line of code](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/api/src/map.ts#L249) that implements the mouseMove Observable, as well as the [MouseEvent](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/api/src/events.ts#L24) it passes, but found no reason to explain this behavior. 

Closing for now, if it pops up again we can look into `Observable.fromEvent` having an issue, or `esriMapElement` is artificially triggering these in some odd scenarios/environments.

**Comment by AleksueiR** [comment] 2018-02-16 12:55
Open Windows Task Manager causes the `mouseMove` events to fire every second since the manager updates itself every second. Only on Windows 7 it seems. 

https://stackoverflow.com/a/17819113

**Comment by milesap** [comment] 2018-02-16 13:11
@AleksueiR asked for the `mApi` to filter emits such that no two back to back emits have the same screen position.

**Closed** 2018-05-01 19:40 UTC
Labels: mApi
