### ISSUE TITLE
Opening a table after its layer is reloaded produces empty rows

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3568] opened 2019-06-10 13:24 UTC
![image](https://user-images.githubusercontent.com/8885149/59197631-c41e8800-8b5f-11e9-8716-e1f592b4860e.png)

To reproduce:
Using http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html?sample=3

Open table -> reload layer -> close table (using `x` until https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3567 is merged) -> open table

The table opens and loads but the rows have no data and the details & zoom buttons don't work. This occurs on dynamic layers.

**Comment by james-rae** [comment] 2019-06-10 15:54
Re-check after https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3509 is done (happening soon)

**Comment by RyanCoulsonCA** [comment] 2019-06-10 20:33
Just re-tested after the fix to #3509 was merged, and the problem still seems to be occurring.

**Comment by RyanCoulsonCA** [comment] 2019-06-14 15:13
When the layer is reloaded, it looks like each item in the attributes array is losing all of it's information.

Here's the attributes array before a reload:
![](https://i.imgur.com/WmnVKbF.png)

And here's the attributes array after a reload:
![](https://i.imgur.com/1R5kycb.png)

This is probably what's causing this issue.

**Comment by RyanCoulsonCA** [comment] 2019-06-26 12:47
To follow up on my last comment, this is occurring because the table is trying to load the attributes before they're actually fully downloaded from the ESRI request, which is messing with the attributes object. See the image below for a quick example:

![](https://i.imgur.com/MIDpI0h.png)

In the picture above, `finished with openTable call` is printed from the enhancedTable, while `done loading attributes...` is printed from geoApi.

As a test, I added a 3 second timeout before calling `openTable`, and the attributes ended up loading properly.

**Comment by james-rae** [comment] 2019-06-26 14:22
A reloaded layer *should* be creating a new layer record. This means the promise that returns attributes is new, so there shouldn't be any old result hanging around.
What I don't know is how the API attributes are managed during a reload.  Guts say either they are being recycled/wiped, and thus getting synchronized after the grid opens (or not being synched at all), or some other part of the API/Grid loading process is not waiting on the attribute loading promise when it should be. Some console logs should be able to sniff it out

**Comment by ShrutiVellanki** [comment] 2019-06-26 14:53
Since [`openTable`](https://github.com/fgpv-vpgf/plugins/blob/master/enhancedTable/index.ts#L97) is called each time on reload and [this line](https://github.com/fgpv-vpgf/plugins/blob/master/enhancedTable/index.ts#L109) creates the table if the `attributes.length > 0` could we also only allow it to pass if all the values are not `undefined`?  So maybe add something like this before it: 

```js
 this.mapApi.layers.attributesAdded.pipe(take_1.take(1)).subscribe(function (attrs) {
                let undefined = true;
                Object.values(attrs.attributes).forEach(val => {
                    if (val !== undefined) {
                        undefined = false;
                    }
                })
                if (attrs.attributes.length > 0 && undefined === false) {
```

If it fails that check with undefined values, we know it'll end up retrying the call to `openTable` again because it'll go to [this line](https://github.com/fgpv-vpgf/plugins/blob/master/enhancedTable/index.ts#L114)

**Comment by RyanCoulsonCA** [comment] 2019-06-27 13:06
> Edit: it was pointed out to me, that something similar was tried and table was stuck in loading state. Maybe adding baseLayer.fetchAttributes() before this line could help to refresh attribute download on each call to openTable.
>
> (We know from here that getAttributes only calls fetchAttributes when there are 0 attributes downloaded but doesn't check for case where attributes are "downloaded" but undefined)

The problem with this is that the attributes are undefined in the promise too, so fetchAttributes will still be loading in the undefined values. 

See example in the picture below. This is a `console.log` of `this._layerProxy.attribs` in `fetchAttributes`.
![](https://i.imgur.com/5ZZk5Q1.png)

**Comment by dane-thomas** [comment] 2019-07-19 15:13
After some further investigation, it looks like trying to reopen the table automatically right after reloading causes the above issue. 

Adding a delay before reopening does seem to fix the problem for the most part but is not ideal since the amount of time before the layer is ready could change.

The other, more reasonable solution would be to just close the table on reload and not attempt to reopen it. This seems to make the table work on subsequent opens and closes without any problems.

**Comment by james-rae** [comment] 2020-01-10 18:49
What is happening (in the case mentioned by Yi Lei directly above. other ones can be attempted to recreate after fix is supplied).

1. `NGP` Layer loads, but is invisible.  The [layer load handler](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.2.0/src/app/geo/layer-registry.service.js#L451) detects the case, an only initializes the API object. The handler remains active.
2. User clicks the `NGP` grid. This requests a download of attributes, though the grid ends up filtering them all for display because layer is still invisible.
3. User makes `NGP` visible. The layer load handler triggers again, this time running the remainder of the logic and deactivating.
4. This causes the Layer API creation to run a second time (see large comment in the code). The code figures out it already has an API object and uses it.  However, it also [re-initializes the object](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.2.0/src/app/geo/layer-registry.service.js#L1016) because it's assuming a reload happened (which did not).
5. The first thing the re-initializer does is [remove the attributes](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.2.0/api/src/layers.ts#L590). This logic also does that in a way that erases all properties but leaves empty objects sitting around, so the geoApi layer thinks it still has data loaded and does not attempt a re-download.
6. Grid then draws with empty attributes, giving the blank party.

Main fix will be to stop calling the Layer API creator twice on the same layer record.
Will investigate a second fix to ensure the behavior of the API attribute remover is doing what it should.

**Comment by yileifeng** [comment] 2021-06-03 17:02
This problem seems to have been fixed by the PRs made by James and Jahid linked above. I tested both of the described methods to reproduce the problem using http://ramp4-app.azureedge.net/legacy/branches/develop/samples/index-samples.html and there are no empty table rows: 

Original problem: 
![Table-Reload1](https://user-images.githubusercontent.com/31557789/120682448-76953700-c46a-11eb-8b9c-e15ec8ba82d8.gif)


2nd instance from https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3568#issuecomment-530926814: 
![Table-Reload2](https://user-images.githubusercontent.com/31557789/120682478-7e54db80-c46a-11eb-86a5-6263d4b5bcb2.gif)

**Closed** 2021-06-14 15:28 UTC
Labels: bug-type: regression, bug-type: unexpected behavior, priority: high, problem: bug, type: corrective
