### ISSUE TITLE
Support for time-enabled WMS layers via RAMP UI

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#331] opened 2016-02-16 13:06 UTC
RAMP should make available a control to iterate through the steps of a time enabled WMS layer.  WMS layers can be controlled on either a per layer basis, or as a global timescale for the map.

Criteria:
- Should be written as a a core plugin to allow replacement of the time slider control
- Should support a per layer time slider and a "all layer" time slider
- Time slider should support ability to go to start or end of timescale as well as iterate forwards or backwards based on the default step.
- Map authors should be able to suppress the use of WMS layers globally for autolegend scenarios
- Map authors should be able to enalbe/disable the use of WMS layer on a per layer basis in thematic map scenarios
- Map authors should be able to enable/disable the "all layer" time slider in both autolegend and thematic map scenarios 
- A global time slider control should be able to interact with time sliders for Esri layers as well

**Comment by alexandreleroux** [comment] 2016-02-16 16:27
Thanks @dan-bowerman  This is a dupe of issue #324 , should #324 be closed?

**Comment by dan-bowerman** [comment] 2016-02-16 16:30
Ah sorry, I had missed these! I will close #324.

**Comment by joseph2rs** [comment] 2016-11-28 15:10
Just to add a little more informations:

Time parameter for WMS Layer can be found on the dimension node of GetCapabilities, example for a Geomet Layer: `<Dimension name="time" units="ISO8601" default="2016-11-28T12:00:00Z" nearestValue="0">2016-11-28T12:00:00Z/2016-12-01T00:00:00Z/PT12H</Dimension>`
- `name` is the name of the dimension, to be passed on the GetMap request
- `default` is the default time provided by the WMS server if no `time` parameter is passed
- The node is organized as follows: `<start time>`/`<stop time>`/`<step>`
(see WMS standard)

So the layer need to be updated periodically from the `<start time>` to the `<stop time>` with adding `<step>` and when `<stop time>` is reaching, back to `<start time>`.

A time-range slider is required to navigate through times, but step-by-step buttons are also useful for precision (if the time range is very long/lot of times).

The speed of animation shall also be adjustable.

Experience when developing a similar feature for OL3:
- The loading time of layer is too long, it result on a jerky view, so we need to pre-load layers.

**Comment by mweech** [comment] 2016-11-30 15:52
@joseph2rs thanks for the feedback.  i was literally just tasking a team member to start a high level analysis on time enabled visualizations (both WMS and non-WMS sources) so this is very good timing!

**Comment by yblain** [comment] 2017-08-22 13:30
Does this issue include the time-enablement of non-WMS services as well? Or should we create a new issue for that?

**Comment by milesap** [comment] 2018-06-07 16:21
This is possible to implement based on support from the esri api in use and assuming a v10+ server. The time needed to implement this well is hard to gauge but it is not trivial. James I'm sure has more background on venturing a guess.

They have a dojo widget we can use that will work out of the box, but we'll likely need to make our own to be accessible and look nice by using the Web APIs to build applications that perform temporal queries, filter layers using time definitions, and set the map's time extent.

As for performance:

> It is not recommended to use the time slider with feature layers in on demand mode because this can result in too many requests to the server. If you are not working with a large amount of data, you can use a feature layer in snapshot mode. If your dataset is large, consider using an ArcGISDynamicMapServiceLayer instead.

Background info: https://developers.arcgis.com/javascript/3/jshelp/inside_temporal.html

**Comment by mweech** [comment] 2019-02-21 20:49
This issue has languished for some time.  Currently, RAMP allows the manipulation of the WMS time variable via API interaction with RAMP.  There is no out of the box support for this manipulation.  This issue should be rescoped to provide **auto-legend** support for time enabled WMS layers.

**Closed** 2019-09-26 17:45 UTC
Labels: addition: feature, needs: more info, type: perfective

**Comment by alexandreleroux** [comment] 2019-10-01 18:44
@dan-bowerman has this ticket been closed because support for time-enabled WMS layers is now supported by RAMP? Thanks for the clarification! :-)

**Comment by dan-bowerman** [comment] 2019-10-04 18:36
@alexandreleroux Sorry, not yet. We are in a mode right now where we are closing out the 2+ year old issues whether they are completed or not -- the number of open issues has become unsustainable so we are doing some major cleanup activities. We may even have repository reboot in the near future -- stay tuned. There is a priority project next fiscal year that will be looking for time enabled layers support, and our team will likely be revisiting this (in a different frame of mind than 2016).

**Comment by alexandreleroux** [comment] 2019-10-09 17:49
big thanks @dan-bowerman for the followup.

Can you tell us how we can track the eventual implementation of this important feature, `support for time-enabled WMS layers`, into RAMP? I'm worried this request gets lost given the ticket is now closed. Thanks!
