### ISSUE TITLE
Some messages hanging after exercising Geolocation Search

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1760] opened 2017-03-09 19:45 UTC
Tested build: http://fgpv.cloudapp.net/demo/v1.6.0-1/prod/samples/index-fgp-en.html?keys=JOSM,Airports,EcoAction,CESI_Other,NPRI_CO,Railways,Barley
Test data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer

This happened when user had a Scale Dependency layer added to FGP Viewer.
- Add above Scale Dependency layer by selecting zoom level 1 to zoom level 4
- Click "Geolocation Search" button
- Enter search text, for example Toronto
- Select any drop down option displayed, for example "Toronto, Peel, ON" (Geographical Area)
- Then click "Close Geolocation Search" button
Put your cursor inside Visualiser on any buttons, including toolbar buttons, or just simply anywhere on the map, you could see some messages hanging on top and on right hand side of the Viewer. Messages will disappear when moving cursor outside of the Viewer.
Below is a screenshot when putting cursor on Geolocation Search button.
![image](https://cloud.githubusercontent.com/assets/18723160/23767319/339d6358-04d6-11e7-9867-b003c819b645.png)

**Comment by jolevesq** [comment] 2017-03-31 14:16
Set layer visibility to false remove the tooltip. When we set visibility again tooltip are gone. Not a solution but may help to solve the problem.

**Comment by milesap** [comment] 2017-03-31 17:27
Not critical for 1.6.1, moving to 1.7.0

**Comment by milesap** [comment] 2017-04-03 16:07
I could not find a suitable solution for this issue. I confirmed `tooltip.decorator.js` is not to blame. Reviewed angular material issues for possible bug reports. Found [this one](https://github.com/angular/material/issues/2791) and others but they may not be related, and if there were a bug it wouldn't be fixed:

From AM team lead:
> This issue is closed as part of our ‘Surge Focus on Material 2' efforts.

Will delay this issue to v2.0+

**Comment by AleksueiR** [comment] 2017-04-07 15:30
This is pretty annoying bug on a major functionality.

**Comment by milesap** [comment] 2017-04-10 16:36
Round two :boxing_glove:

**Comment by milesap** [comment] 2017-04-12 13:45
Ok'd by @mweech to cancel v1.6.2 and move straight to v1.7.0

**Comment by milesap** [comment] 2017-04-13 17:41
This will forever be a mystery. Inside `entry-control-button.html` there's this:

```html
<md-tooltip ng-if="self.template.tooltip" md-direction="top">{{ self.isFunction(self.template.tooltip) ? self.template.tooltip(self.control.value) : self.template.tooltip | translate }}</md-tooltip>
```

This is the source of the unwanted tooltips. Maybe determine if the `ng-if="self.template.tooltip"` should be `false` in the cases where they are being shown all over the place.

**Comment by milesap** [comment] 2017-06-14 13:00
Will test once #1976 is resolved (no geo searches atm)

**Comment by milesap** [comment] 2017-06-14 13:51
No longer an issue on my machine (Chrome), moving to QA for a more thorough re-evaluation.

**Comment by AleksueiR** [comment] 2017-06-15 13:33
Self-fixing bug :) We need more of those.

**Comment by IsabellaPan** [comment] 2017-06-28 13:47
Tested Jun 27 daily build: http://fgpv.cloudapp.net/demo/v2.0.0-daily09/prod/samples/index-samples.html
It is still an issue for both Chrome and Firefox. Not seen any fixes.

**Comment by AleksueiR** [comment] 2017-06-28 14:33
@milesap Can you double check?

**Comment by milesap** [comment] 2017-07-10 15:06
It's back for me too

**Comment by AleksueiR** [comment] 2017-07-18 15:01
Traced it to this line here: https://github.com/barryytm/fgpv-vpgf/blob/develop/src/app/geo/geo-search.service.js#L483

It seems that geo search tries to zoom "to close" (whatever it means), and that somehow interferes with Angular Material library which generates duplicate tooltips. Changing the `expand` to 2 mostly solves the problem. 

Also, I noticed that duplicate tooltips never created on Mercator maps. Maybe geoSearch tries to zoom past the lowest zoom level on Lambert maps and "bounces" back, which messes with Angular. Mercator maps have more zoom levels, so it doesn't bounce and doesn't produce duplicate tooltips.

I asked @james-rae to check if it's possible to use the same logic geoApi uses to select the get zoom level when zooming to features.

**Comment by james-rae** [comment] 2017-07-19 17:50
These branches have a working prototype with terrible hack architecture
https://github.com/james-rae/fgpv-vpgf/tree/searchzoom
https://github.com/james-rae/geoApi/tree/searchzoom

Proper solution will involve decoupling the zoom logic from the `AttribFC` class.  Zoom logic should exist as a static function in geoApi, and take a geometry as parameter.  `AttribFC.zoomToGraphic` should execute fetching a graphic then call the static zoom function.  The geo-search will also call the static zoom function, passing in the result extent

**Comment by james-rae** [comment] 2017-08-28 20:20
After wiring in the zoom-to-feature logic to the geosearch result, I noticed the following

The issue still happens when zooming to a search result.  However, if I load a polygon layer and do a zoom to feature on it, I cannot reproduce the error; even though the exact same code to reposition the map is executing, and the result goes to the same scale level.

This leads me to believe that something unique to the geosearch is affecting the situation.

Some possible paths forward

- Further debugging on what is truely causing this
- If we are certain that not zooming down to a given scale level will prevent this, we could write some terrible code to prevent it.  Would need to take resolution, extent size, and on-screen map size, pre-calculate where a zoom would end up, and adjust level if too low. Bad news.

Layer to test with to show that issue does not happen using regular zoom to feature:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/Common/CommonGIS_AuxMerc/MapServer/1
Do a quickzoom on the feature where `DUID = 'L4J'` (ether via grid filter or by identify click on toronto area).

Also, not certain if even worth keeping the logic switch to use zoom to feature.  It uses same call that current geosearch uses (`map.setExtent`). And since it's a rectangle with no scale dependencies, all the other extra logic in zoom-to-feature is never used.

**Comment by AleksueiR** [comment] 2017-09-18 18:16
More details: 

- Import http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer selecting `Zoom level 4`
   - Zooming to "Toronto, Peel" from default extent produces multiple tooltips when geosearch is closed
- Import http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer selecting `Zoom level 3`
   - Zooming to "Toronto, Peel" from default extent does not produce multiple tooltips when geosearch is closed

`Zoom level 4` is scale dependent and is visible at the same level as the zoomed in search results; it's not visible at the default extent. 

> __It seems that multiple tooltips are only produced when the extent changes and there is such a layer so it's not visible at the initial extent, and visible at the zoomed-in extent.__

Try this, load `Zoom level 4`, zoom manually to where it become visible, and try zooming to "Toronto, Peel" - no tooltips. Zoom a couple levels up so `Zoom Level 4` is invisible, and try zooming to "Toronto, Peel" - boom!, tooltips.

I think this is good, since it limits the scale of this bug. 

Will check next what happens when the layer passes it's scale dependency threshold.

**Comment by AleksueiR** [comment] 2017-09-18 18:45
Okay, getting closer:
- Import http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer selecting `Zoom level 4`
- open geosearch component, but not do anything
- zoom in manually to the level where `Zoom Level 4` is visible
- clikc the close button of the geosearch component
- boom! tooltips

If you open/close geo search component after zooming in, nothing happens.

**Comment by AleksueiR** [comment] 2017-09-21 12:06
Fix is in PR. :horse:

**Closed** 2017-10-27 14:49 UTC
Labels: browser: Chrome, browser: Foxes, bug-type: unexpected behavior, priority: high, problem: bug
