### ISSUE TITLE
Support for WMS additional styles

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#332] opened 2016-02-16 13:08 UTC
Consult GeoMet Team (@alexandreleroux and @tomkralidis for more information about this potential requirement. WMS layers can be styled in many different ways and expose several of these options in their Capabilities -- how can we best ingest and handle multiple style configurations for the same layers?

**Comment by alexandreleroux** [comment] 2016-02-16 16:29
Thanks @dan-bowerman This is a dupe of issue #327 , should #327 be closed? If you consult Tom K, please keep me in the loop, as GeoMet is a joint project. Thanks -- Alex

**Comment by dan-bowerman** [comment] 2016-02-16 16:34
For reference: [GeoMet](http://www.ec.gc.ca/meteo-weather/default.asp?lang=En&n=C0D9B3D8-1#wms)

**Comment by jolevesq** [comment] 2016-09-01 19:40
This can be useful https://geonet.esri.com/thread/87349

**Comment by mweech** [comment] 2017-10-03 18:40
Our suspicion is that given WMS Styles are an extension to the original WMS spec, supporting this will require overriding Esri API requests for WMS layers as the API does not currently support this extension.

**Comment by alexandreleroux** [comment] 2017-10-05 14:39
Styles are not an extension of the WMS standard, it's actually a Mandatory WMS GetMap Request parameter, see section 7.3.2 of the WMS Implementation Specification: http://portal.opengeospatial.org/files/?artifact_id=14416 Am I mistaken? In light of this can you please reassess the importance of this request which would increase compliance of the FGPV with the WMS standard?

In a nutshell, as specified in section 7.3.3.4 of the same document, numerous Styles can be made available for a single WMS layer. This feature request is to allow the user to switch from the default style to another one of the available WMS styles as advertized by the WMS server. Nothing outside the WMS standard is being involved here. Makes sense? Thanks :-) -- Alex

**Comment by JahidAhmed** [comment] 2017-10-05 14:51
@alexandreleroux Yes, what you have mentioned is correct. I have looked into this and am currently working on it!

**Comment by mweech** [comment] 2017-10-05 17:36
@alexandreleroux Hi, Alex! Happily you are correct.  This was only a suspicion at first as we revived this issue.  We have run into these kind of challenges in the past with extensions that were commonly believed to be "standard", while Esri quite clearly has decided to stick very strictly to the "no extensions, just the standard" support.  

@JahidAhmed  already mocked up a PoC using GeoMet where he could select the various styles for a layer so now we can put this in the queue to become a reality.

**Comment by alyec** [comment] 2017-10-05 18:06
Sorry, I believe I was thinking about [SLD](http://www.opengeospatial.org/standards/sld) when I was talking about extensions and getting stuff confused.  If the basic styling is supported by ESRI that makes life a lot easier.

**Closed** 2017-12-11 16:05 UTC
Labels: addition: feature
